#!/usr/bin/env bash
set -euo pipefail

# Portable deployment policy:
#
# The supported first-deployment flow is intentionally browser-only.
# This script does NOT create Railway Projects, Domains, TCP Proxies, or
# redeployments. Do not place a Railway API token in this repository or use
# this script as part of container startup.
#
# First deployment:
#   1. Deploy the repository from the README Railway button.
#   2. Allow the first deployment to fail because networking is not configured.
#   3. Railway Settings -> Networking -> Generate Domain -> target 8080.
#   4. Railway Settings -> Networking -> TCP Proxy -> target 8080.
#   5. Manually click Deploy/Redeploy again.
#   6. Verify /health, /ready, the generated subscription, and client nodes.
#
# This file is retained only as a safety/documentation guard so older tooling
# cannot silently reintroduce the retired local/API provisioning workflow.

echo "[provision] Local/API auto-provisioning is disabled for this portable build."
echo
cat <<'EOF'
Use the Railway web UI for first deployment:

  1. Settings -> Networking -> Generate Domain
     Target/application port: 8080

  2. Settings -> Networking -> TCP Proxy
     Target/application port: 8080
     External port: generated by Railway; never hard-code it.

  3. Click Deploy/Redeploy manually.

The running container consumes:
  RAILWAY_PUBLIC_DOMAIN
  RAILWAY_TCP_PROXY_DOMAIN
  RAILWAY_TCP_PROXY_PORT
  RAILWAY_TCP_APPLICATION_PORT=8080

No Railway API token is required by the application.
EOF
