#!/usr/bin/env bash
set -euo pipefail

# Provisioning helper for railway-v1.0-8080-portable.
# This script does NOT hard-code a public domain or TCP proxy port.
# Railway creates those values; the runtime consumes the resulting variables.
#
# Prerequisites:
#   - Railway CLI installed and authenticated (`railway login`)
#   - A Railway project/service selected or created
#   - The service deployed from this repository
#
# The control-plane actions are intentionally kept outside the container.
# After networking is created, the container reads:
#   RAILWAY_PUBLIC_DOMAIN
#   RAILWAY_TCP_PROXY_DOMAIN
#   RAILWAY_TCP_PROXY_PORT
#   RAILWAY_TCP_APPLICATION_PORT
#
# Railway's TCP Proxy target/application port must be 8080.

APP_PORT="${RAILWAY_TCP_APPLICATION_PORT:-8080}"
if [[ "$APP_PORT" != "8080" ]]; then
  echo "[provision] ERROR: TCP application target must be 8080; got: $APP_PORT" >&2
  exit 1
fi

echo "[provision] Railway service target port: 8080"
echo "[provision] Next control-plane steps:"
echo "  1. Generate the Railway public domain for this service."
echo "  2. Create a TCP Proxy targeting application port 8080."
echo "  3. Deploy/redeploy the service."
echo "  4. Verify the runtime exposes the Railway-provided variables."

echo
cat <<'EOF'
Expected runtime variables (values are generated by Railway):
  RAILWAY_PUBLIC_DOMAIN
  RAILWAY_TCP_PROXY_DOMAIN
  RAILWAY_TCP_PROXY_PORT
  RAILWAY_TCP_APPLICATION_PORT=8080

Do not replace these with fixed hostnames or ports.
EOF
