#!/usr/bin/env bash
set -euo pipefail

# Portable deployment policy:
#
# This helper intentionally does not call the Railway API and never creates
# Projects, Domains, TCP Proxies or redeployments. Railway networking remains
# a control-plane operation performed in the Railway UI.
#
# The container itself does not require the Public Domain or TCP Proxy to be
# present at process start. runtime_discovery.py consumes whatever Railway
# currently exposes and records the current state without inventing values.

echo "[provision] Railway control-plane provisioning is intentionally disabled."
echo
cat <<'EOF'
Deploy the repository as a new Railway service.

Optional networking:
  1. Settings -> Networking -> Generate Domain -> target the service PORT.
  2. Settings -> Networking -> TCP Proxy -> target the same service PORT.
     The external TCP port is generated by Railway; never hard-code it.

The container dynamically consumes:
  PORT
  RAILWAY_PUBLIC_DOMAIN
  RAILWAY_TCP_PROXY_DOMAIN
  RAILWAY_TCP_PROXY_PORT
  RAILWAY_TCP_APPLICATION_PORT
  RAILWAY_PROJECT_ID / ENVIRONMENT_ID / SERVICE_ID / REPLICA_ID

No Railway API token is required by the application.
EOF
